CREATE TABLE MATRICULAS (
   id SERIAL NOT NULL,
   aluno_id INTEGER,
   data_da_matricula TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_matricula PRIMARY KEY (id)
);

ALTER TABLE MATRICULAS ADD CONSTRAINT FK_MATRICULA_ON_ALUNO FOREIGN KEY (aluno_id) REFERENCES ALUNOS (id);

CREATE TABLE AVALIACAO_FISICA (
   id SERIAL NOT NULL,
   aluno_id INTEGER NOT NULL,
   data_da_avaliacao TIMESTAMP WITHOUT TIME ZONE,
   peso DOUBLE PRECISION NOT NULL,
   altura DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_avaliacao_fisica PRIMARY KEY (id)
);

ALTER TABLE AVALIACAO_FISICA ADD CONSTRAINT FK_AVALIACAO_FISICA_ON_ALUNO FOREIGN KEY (aluno_id) REFERENCES ALUNOS (id);